### ISSUE TITLE
Deployment error on Vercel

### ISSUE THREAD

**Issue by NathanLandsX** [PhilDL/astro-starter-ghost#12]
Hi, I've added this template to an existing code base. Locally everything works fine and pulls in all of my posts etc. but when I try to push to Vercel, I get this error:
`--error   Failed to parse URL from undefined/ghost/api/v3/content/posts/?key=undefined&include=authors,tags`

**Comment by PhilDL** [comment]
Hi, sorry for the delayed answer, I guess you solved it on your own.

For other people seeing this issue please check your Vercel project settings, "Environnement Variables" tab:

![CleanShot 2022-12-13 at 07 15 03](https://user-images.githubusercontent.com/4941205/207217717-3b721ec7-23b9-415b-bf0c-250837229033.png)
