### ISSUE TITLE
Syncing with Pages too, not just Posts

### ISSUE THREAD

**Issue by ghost** [PhilDL/astro-starter-ghost#13]
I've tried creating a `[slug].astro` file under pages with mostly the same code for posts, but replacing `post` with `page` assuming that something would work.

Only thing I've been successful with, is listing the existing pages that I have in Ghost, but not able to create the pages themselves with their content.

**Comment by PhilDL** [comment]
Do you have an example repo to share ?

In the example code `[slug].astro` gather posts **and pages**, for example from this repository there is that "About page" https://astro-starter-ghost.netlify.app/about/ and it is rendered. Did you publish your page from Ghost backend?

**Comment by ghost** [comment]
On second thought, yeah I'm doing a lot wrong here on my end. I'll going to just rebuild on top of this starter. Sorry about all that.
