### ISSUE TITLE
Any way to do deploy this on netlify with local ghost?

### ISSUE THREAD

**Issue by MelleNi** [PhilDL/astro-starter-ghost#16]
Is there any way to deploy this on netlify with local ghost? I'm sending commits to github, but it obviously doesn't include any of the ghost content

**Comment by PhilDL** [comment]
Hi ! Maybe you could up your local server and use [ngrock](https://ngrok.com/) to tunnel your localhost to the internet, you will then fill the env variables in your GitHub repository secret.
