### ISSUE TITLE
Not an issue, just a thank you!

### ISSUE THREAD

**Issue by endymion1818** [PhilDL/astro-starter-ghost#3]
This is awesome, thanks so much for creating a starter for Astro. Ghost is one of my go-to blogging platforms and so I'm extremely happy about being able to get started with it quickly using Astro.

**Comment by PhilDL** [comment]
Thank you so much for your kind words, it means a lot to me! Feel free to open any other issues or PR if you find bugs or improvements, i am learning by doing and this repo will change often since Astro is pretty new and changing quickly.
